// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }


// "use client"; // Ensure the layout is treated as a Client Component

// import { CartProvider } from "@/context/CartContext";
// import "./globals.css";

// export default function RootLayout({
//     children,
// }: {
//     children: React.ReactNode;
// }) {
//     return (
//         <html lang="en">
//             <body>
//                 <CartProvider>{children}</CartProvider>
//             </body>
//         </html>
//     );
// }

"use client"
import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/Footer";
import { CartProvider } from "@/context/CartContext";
// Import your CartProvider


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {/* Wrap children with CartProvider */}
        <CartProvider>
          {children}
        </CartProvider> 
        <Footer />
      </body>
    </html>
  );
}
